### ISSUE TITLE
data_member_spec should be called nsdm_description

### ISSUE THREAD

**Issue by ilazaric** [bloomberg/clang-p2996#1]
https://github.com/bloomberg/clang-p2996/blob/d76d653722eaa7d6b45948f6e57967fb78302314/libcxx/include/experimental/meta#L769

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2023/p2996r1.html#nsdm_description-define_class

**Comment by katzdm** [comment]
Hey, @ilazaric ! We changed the name to `data_member_spec` in the R2 revision of the paper, following some negative feedback re: the `nsdm` acronym, and after adding the ability to define static data members.

https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p2996r2.html#data_member_spec-define_class

Some of the design decisions and names are still a bit of a moving target, though I expect they'll settle as the paper progresses.

**Comment by ilazaric** [comment]
Ah, I missed the updated version of the proposal, TY
