### ISSUE TITLE
Some p2996r7's Compiler Explorer examples currently need adding -freflection-latest and replacing ^ by ^^

### ISSUE THREAD

**Issue by fzuuzf** [bloomberg/clang-p2996#107]
A fixed  "Named Tuple": https://godbolt.org/z/hzGM7cadT

**Comment by katzdm** [comment]
Thanks! I should be using the `LIFT` macro there to switch on `^` or `^^` based on the presence of `-freflection-latest`. Just pushed a fix. Appreciate the bug report!
