### ISSUE TITLE
Compilation is broken

### ISSUE THREAD

**Issue by Yaraslaut** [bloomberg/clang-p2996#110]
master is broken: https://godbolt.org/z/dznddM8hc

commit that broke it: https://github.com/bloomberg/clang-p2996/commit/5a5e1a48f55d34ac669e3a08235c66bd39fcc046

I could not figure out exactly what is causing this error since generated errors are not pointing to the [libcxx/include/experimental/meta](https://github.com/bloomberg/clang-p2996/commit/5a5e1a48f55d34ac669e3a08235c66bd39fcc046#diff-387578b52cd59053940e77c269d0cf20edae1b226f1e2d427ed12837bb490a71) file but to generated meta header

**Comment by katzdm** [comment]
Sorry about that - forgot to wrap in `LIFT(x)` instead of `^^x`, so it works for both `^x` and `^^x`. Adding `-freflection-latest` will work around this for today; should be fixed tomorrow.
