### ISSUE TITLE
Cannot build from source

### ISSUE THREAD

**Issue by ghost** [bloomberg/clang-p2996#116]
[deleted]

**Comment by katzdm** [comment]
Hey! I think the build of lldb in particular is broken - there was a PR a while back to try to fix that, but the contributor didn't have time to see it through. Try removing lldb from the list of enabled projects, and let me know if that works.

**Comment by githubuser6000** [comment]
That seems to have worked! Thank you!

**Comment by githubuser6000** [comment]
Unrelated question perhaps. Does clangd work with the reflection stuff? I can't seem to get it to work properly.
