### ISSUE TITLE
Instructions on how to build a docker container?

### ISSUE THREAD

**Issue by lemire** [bloomberg/clang-p2996#18]
It would quite sweet to be able to generate a docker container. This would allow us to experiment.

**Comment by katzdm** [comment]
Hey, @lemire ! I haven't tried to build a docker container for this project, but it _should_ be the same process as for any other clang compiler. In case it's helpful, here's the magic spell that I've used to build for Linux.

```bash
cmake -G "Ninja" -S llvm -B build-llvm -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_UNREACHABLE_OPTIMIZE=ON \
    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
    -DLLVM_ENABLE_PROJECTS=clang
```

Let me know if you have any luck! And don't forget, you can also play around with the compiler on [godbolt](https://godbolt.org/z/Ejeh8vWYs).

**Comment by lemire** [comment]
> you can also play around with the compiler on [godbolt](https://godbolt.org/z/Ejeh8vWYs).

I know, and that's great, but that's somewhat limited. We would like to build whole prototypes.

**Comment by lemire** [comment]
Ah Ah.

Using *precisely* your command works...

```
cmake -G "Ninja" -S llvm -B build-llvm -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DLLVM_UNREACHABLE_OPTIMIZE=ON \
    -DLLVM_ENABLE_RUNTIMES="libcxx;libcxxabi;libunwind" \
    -DLLVM_ENABLE_PROJECTS=clang
cmake --build build-llvm -j
```

Great.

**Comment by lemire** [comment]
So we should be able to turn it into docker container then.

**Comment by katzdm** [comment]
Great to hear! I'll go ahead and close this one.

**Comment by lemire** [comment]
@katzdm Thanks.

**Comment by lemire** [comment]
In case someone finds this issue... you can find a recipe for a docker container at https://github.com/lemire/docker_programming_station/tree/master/clangp2996

See the README file for further instructions. The gist of it is that you can build a docker container from the current version of this repo and build projects with it.
