### ISSUE TITLE
std::meta::members_of cannot be called in a constexpr context

### ISSUE THREAD

**Issue by sturcotte06** [bloomberg/clang-p2996#36]
I'm trying to iterate over members of a struct and I can't retrieve the members in a `constexpr` context. In the P2996 paper, they have this example:

```cpp
struct member_descriptor
{
  std::size_t offset;
  std::size_t size;
};

template <typename S>
consteval auto get_layout() {
  constexpr auto members = nonstatic_data_members_of(^S);
  std::array<member_descriptor, members.size()> layout;
  for (int i = 0; i < members.size(); ++i) {
      layout[i] = {.offset=offset_of(members[i]), .size=size_of(members[i])};
  }
  return layout;
}
```

But I can't make it work. Here is a link to the issue: https://godbolt.org/z/zdzKhP94T

**Comment by katzdm** [comment]
Hey @sturcotte06 ! Thanks for the report.

We could do a better job calling this out in the paper, but the example isn't valid with only `(C++23 + P2996)` - It in fact requires a further change (i.e., [P3032](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2024/p3032r0.html) - "_Less transient constexpr allocation_"), which is on track for C++26 but hasn't yet been voted into the working draft.

I won't be implementing P3032 support on this fork - once it's merged into the working draft, it will eventually be implemented in upstream clang, and we'll pick it up here through a merge from upstream.

Fortunately, the workaround in the meantime is fairly straightforward:
1. Remove the `constexpr` on the declaration of `members`.
2. Replace `members.size()` with `nonstatic_data_members_of(^S).size()` in the declaration of `layout`.

You can see that working [here](https://godbolt.org/z/oeWozEzxj).

**Comment by SuibianP** [comment]
I encountered something similar when trying to use the `std::ranges::views::transform` adaptor. I suspect it to also be related to P3032, but fail to see why, since it all resides within one single `constexpr` evaluation context.

```c++
#include <experimental/meta>
#include <ranges>
#include <print>
#include <vector>

using namespace std;

struct s {
    int v1;
    long long v2;
};

consteval auto names() {
    return nonstatic_data_members_of(^s) |
        views::transform(meta::identifier_of) |
        ranges::to<vector>();
}

int main() {
    print("{}", names()[0]);
}
```

Using a `constexpr` lambda yields the same effect.
