### ISSUE TITLE
Implement is_noexcept metafunction

### ISSUE THREAD

**Issue by katzdm** [bloomberg/clang-p2996#45]
The `is_noexcept` metafunction was added in P2996R3.

**Comment by BaLiKfromUA** [comment]
~~Planning to implement this function, seems doable + there are a couple of similar metafunctions implemented already to take as an example.~~

~~Let me know if there are any objections.~~

Update: Kirill Delimbetov messaged me that he is working on this task already, I will try to implement #44 instead.
