### ISSUE TITLE
Expanding over members of the global namespace crashes

### ISSUE THREAD

**Issue by KendallHarter** [bloomberg/clang-p2996#82]
**Describe the bug**
Trying to expand over `std::meta::members_of(^::)` results in a crash.

**To Reproduce**
The source code:
```cpp
#include <experimental/meta>

namespace __impl {
  template<auto... vals>
  struct replicator_type {
    template<typename F>
      constexpr void operator>>(F body) const {
        (body.template operator()<vals>(), ...);
      }
  };

  template<auto... vals>
  replicator_type<vals...> replicator = {};
}

template<typename R>
consteval auto expand(R range) {
  std::vector<std::meta::info> args;
  for (auto r : range) {
    args.push_back(reflect_value(r));
  }
  return substitute(^__impl::replicator, args);
}

consteval auto test()
{
  [:expand(std::meta::members_of(^::)):] >> [&]<std::meta::info>() {};
}
```

The command:
```
clang++ -stdlib=libc++ -std=c++26 -freflection test.cpp
```

**Expected behavior**
Compiler does not crash and allows expanding over the global namespace.

**Additional context**
I tried to narrow down what in the global namespace is causing a crash, but I couldn't replicate it with a smaller testing namespace.

**Comment by katzdm** [comment]
Hey @KendallHarter - Thanks for the bug report! I can reproduce on my end; I'll look at this now.

**Comment by katzdm** [comment]
@KendallHarter I've just fixed this at HEAD, and it should work on Godbolt tomorrow.

Note that calling `expand` over the members of the global namespace will likely trigger the instantiation of a template with a huge number of template arguments. Clang caps the number of allowed template arguments to 256 by default, but you can use `-fbracket-depth=<NUM_ARGS>` to toggle that number - I found that setting `-fbracket-depth=1500` was sufficient to make this build on my laptop (but your mileage may vary, especially according to the headers that you include).

Thanks again for the bug report!
