### ISSUE TITLE
Expanding on members of a namespace with partial template specialization crashes

### ISSUE THREAD

**Issue by KendallHarter** [bloomberg/clang-p2996#83]
**Describe the bug**
Expanding on `std::meta::members_of` a namespace with partial template specialization crashes the compiler.

**To Reproduce**
Source file:
```cpp
#include <experimental/meta>

namespace __impl {
   template<auto... vals>
   struct replicator_type {
      template<typename F>
      constexpr void operator>>(F body) const {
         (body.template operator()<vals>(), ...);
      }
   };

   template<auto... vals>
   replicator_type<vals...> replicator = {};
}

template<typename R>
consteval auto expand(R range) {
   std::vector<std::meta::info> args;
   for (auto r : range) {
      args.push_back(reflect_value(r));
   }
   return substitute(^__impl::replicator, args);
}

namespace test_namespace {
   template<typename>
   struct empty {};

   template<typename>
   struct test_struct;

   template<typename T>
   struct test_struct<empty<T>> {};
}

consteval void test()
{
   [:expand(std::meta::members_of(^::test_namespace)):] >> []<auto> {};
}
```

Command:
```
clang++ -stdlib=libc++ -std=c++26 -freflection test2.cpp
```

**Expected behavior**
Expanding over the members of a namespace with a partial template specialization should not crash the compiler.

**Environment**
Ubuntu 22.04.4 LTS 
```
> clang++ --version
clang version 20.0.0git (https://github.com/bloomberg/clang-p2996.git b62d82c4e02d28f55b099a06ab44d6a9a370bf39)
Target: x86_64-unknown-linux-gnu
```

**Comment by katzdm** [comment]
Thanks again! Fixed this one too. Probably not too surprising, but similar crashes could be triggered using partial variable template specializations.

Note that reflections of partial template specializations should not be representable with reflections at all - we could probably stand to word that more clearly in P2996 (especially re: `members_of` and friends).

Appreciate the bug reports! Let me know what others you find.
