### ISSUE TITLE
Calling value_of on a reflected function crashes

### ISSUE THREAD

**Issue by KendallHarter** [bloomberg/clang-p2996#84]
**Describe the bug**
Calling `value_of` on a reflected function crashes.

**To Reproduce**
Code:
```cpp
#include <experimental/meta>

void test() {}

int main()
{
   std::meta::value_of(^test);
}
```
Command:
```
./bin/clang++ -stdlib=libc++ -std=c++26 -freflection -fparameter-reflection test.cpp
```

**Expected behavior**
I believe this should be a compile error as a function reflection doesn't have a value, but either way the compiler shouldn't crash.

**Comment by katzdm** [comment]
Thanks again! This is now fixed at HEAD.

I could see an argument for returning `value_of(^test) == std::meta::reflect_value(&test)`, but that's not currently what's spec'd, and it might be a bit too niche to bother with for now. Can always define the behavior at a later time.
