### ISSUE TITLE
`type_of` metafunction should dealias the type

### ISSUE THREAD

**Issue by katzdm** [bloomberg/clang-p2996#91]
P2996R6 will change `type_of` to no longer return reflections representing `$typedef-name$`s - instead, a reflection of the underlying type will be returned (see [here](https://godbolt.org/z/eqhGTWMda)).

The `type_of` function is implemented [here](https://github.com/bloomberg/clang-p2996/blob/e97e8c2eeab71377c4b1a5cbd54deb3c9a020c1e/clang/lib/Sema/Metafunctions.cpp#L2000-L2054), and we should also update the `return_type_of` metafunction (proposed by P3096), implemented [here](https://github.com/bloomberg/clang-p2996/blob/e97e8c2eeab71377c4b1a5cbd54deb3c9a020c1e/clang/lib/Sema/Metafunctions.cpp#L5557-L5590).

We have an [existing `desugarType` utility](https://github.com/bloomberg/clang-p2996/blob/e97e8c2eeab71377c4b1a5cbd54deb3c9a020c1e/clang/lib/Sema/Metafunctions.cpp#L839-L874) in `Metafunctions.cpp` that often helps with tasks like these - there is an `UnwrapAliases` argument that should be set to `true`.

[libcxx reflection tests](https://github.com/bloomberg/clang-p2996/tree/p2996/libcxx/test/std/experimental/reflection) should of course be updated to reflect this change.

**Comment by changkhothuychung** [comment]
Hi, its Nhat. picking this up.
