### ISSUE TITLE
Enforce structural type constraint of 'reflect_value' via requires clause

### ISSUE THREAD

**Issue by katzdm** [bloomberg/clang-p2996#92]
For the function

```cpp
template <typename T>
  consteval info reflect_value(T expr);
```

the type `T` must be a [_structural type_](https://eel.is/c++draft/temp.param#7). In P2996R5, we specify this constraint as a "_Constant when_" clause (meaning that the expression fails to be constant if it's not met), but LEWG has asked that it's instead specified as a "_Mandates_" clause (meaning that it's enforced at substitution-time instead). This change will be in P2996R6.

In practice, this means that instead of enforcing the requirement in the metafunction implementation of `reflect_result` ([as we do now](https://github.com/bloomberg/clang-p2996/blob/3ee03ae8ff17558b17db931731e8693050bbc105/clang/lib/Sema/Metafunctions.cpp#L4448-L4450)), we should enforce it in the [`requires`-clause](https://github.com/bloomberg/clang-p2996/blob/3ee03ae8ff17558b17db931731e8693050bbc105/libcxx/include/experimental/meta#L1323) of `reflect_value` in `<experimental/meta>`.

The only tricky thing here is that the Standard Library doesn't currently surface a function for checking whether a type is structural. So probably the easiest thing to do is:

1. Implement a metafunction for `is_structural_type`.
2. Call the `__metafunction` intrinsic directly from the `requires` clause of `reflect_value`, but don't surface it through a `std::` function.

So the template head for `reflect_value` should then look something like:

```cpp
template <typename T>
    requires (!is_reference_v<T> &&
              __metafunction(detail::__metafn_is_structural_type, LIFT(T))
```

**Comment by delimbetov** [comment]
picking up
